### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by Almaz-KG** [sarxos/medusa-system#8]
Please, describe how to install and run this project on IDE (Netbeans, Eclipse, IDEA)

**Comment by sarxos** [comment]
This is Maven project and it's independent from IDE. In Netbeans and Eclipse you can just select _Import Maven Project_ and you are free to go. Don't know about IDEA since I never used it.

I remember there were some prerequisites before the project can work normally (some historical quotes data from bossa.pl had to be imported into MySQL), but it was so long time ago I do not remember any more how to do it. Unfortunately most of the knowledge and tools related to this project evaporated with my old PC which had burn down few years ago :(
